name: Integrar branch master
on:
  push:
    branches:
      - develop

jobs:
  job1:
    if: ${{ endsWith(github.event.head_commit.message, 'release.') }}
    name: Merge de master al ambiente de develop
    runs-on: ubuntu-latest
    steps:
      - name: git checkout release
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Merge desarrollo -> develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: main
          target-branch: develop
      - name: crear rama release a partir de desarrollo
        run: |
          git checkout -b release
          git push -f -u origin release

  job2:
    needs: job1
    name: Merge del ambiente de develop a master
    runs-on: ubuntu-latest
    steps:
      - name: Merge temporal -> desarrollo
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: main
      - name: Merge desarrollo -> release
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: main
          target-branch: release
